#!/usr/bin/env node
// gen-content.mjs — codegen for @snugprotocol/knowledge.
//
// Walks prompts/**/*.{md,txt,py,html,json} (vendored files included) and emits:
//   src/generated/content.ts               — PROMPT_FILES: posix-relative path -> raw content
//   src/generated/skill-creator.sha256.json — sha256 manifest of every vendored file
//
// Both outputs are committed; the content-drift and vendored-checksum tests fail when the
// committed outputs no longer match a regeneration. Deterministic: paths sorted, values
// JSON-string encoded (safe for arbitrary text content).
//
// This file is the ONLY place allowed to touch the filesystem for prompt content — the
// exported package API reads the generated module and stays browser-safe (ADR-0004).

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PROMPT_EXTENSIONS = new Set(['.md', '.txt', '.py', '.html', '.json']);

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const defaultPromptsDir = path.join(packageRoot, 'prompts');
const generatedDir = path.join(packageRoot, 'src', 'generated');

/** Recursively list absolute file paths under dir, sorted for determinism. */
function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile()) out.push(full);
  }
  return out.sort();
}

const toPosix = (p) => p.split(path.sep).join('/');

/** All prompt-store files as { rel (posix, from prompts/), abs }, sorted by rel. */
export function collectPromptFiles(promptsDir = defaultPromptsDir) {
  if (!existsSync(promptsDir)) return [];
  return walk(promptsDir)
    .filter((abs) => PROMPT_EXTENSIONS.has(path.extname(abs).toLowerCase()))
    .map((abs) => ({ rel: toPosix(path.relative(promptsDir, abs)), abs }))
    .sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
}

/** Source text of src/generated/content.ts. */
export function buildContentModuleSource(promptsDir = defaultPromptsDir) {
  const files = collectPromptFiles(promptsDir);
  const lines = [
    '// AUTO-GENERATED by scripts/gen-content.mjs — DO NOT EDIT BY HAND.',
    '// Regenerate with `pnpm gen:content` after any change under prompts/.',
    '// Keys are posix paths relative to prompts/; values are the raw file contents',
    '// (JSON-string encoded at generation time — safe for arbitrary content).',
    '',
    'export const PROMPT_FILES: Record<string, string> = {',
    ...files.map(({ rel, abs }) => `  ${JSON.stringify(rel)}: ${JSON.stringify(readFileSync(abs, 'utf8'))},`),
    '};',
    '',
  ];
  return lines.join('\n');
}

/**
 * Source text of src/generated/skill-creator.sha256.json — sha256 of EVERY file under
 * prompts/skills/skill-creator/ (all extensions: the vendored tree is verbatim), keyed by
 * posix path relative to the skill-creator root.
 */
export function buildChecksumManifestSource(promptsDir = defaultPromptsDir) {
  const vendoredDir = path.join(promptsDir, 'skills', 'skill-creator');
  const manifest = {};
  if (existsSync(vendoredDir)) {
    for (const abs of walk(vendoredDir)) {
      const rel = toPosix(path.relative(vendoredDir, abs));
      manifest[rel] = createHash('sha256').update(readFileSync(abs)).digest('hex');
    }
  }
  const sorted = Object.fromEntries(
    Object.entries(manifest).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  );
  return `${JSON.stringify(sorted, null, 2)}\n`;
}

function main() {
  if (!existsSync(defaultPromptsDir)) {
    console.warn(`[gen-content] prompts/ not found at ${defaultPromptsDir} — emitting empty store.`);
  }
  mkdirSync(generatedDir, { recursive: true });
  const contentPath = path.join(generatedDir, 'content.ts');
  const manifestPath = path.join(generatedDir, 'skill-creator.sha256.json');
  writeFileSync(contentPath, buildContentModuleSource());
  writeFileSync(manifestPath, buildChecksumManifestSource());
  const count = collectPromptFiles().length;
  console.log(`[gen-content] wrote ${toPosix(path.relative(packageRoot, contentPath))} (${count} files) and skill-creator.sha256.json`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
