// @snugprotocol/protocol — the Snug envelope protocol: zod schemas, typed helpers,
// and the single home of every wire constant. Source of truth for snugprotocol/spec
// (see docs/engineering/SPEC_SYNC.md). Browser-safe; runtime dependency: zod only.

export {
  CDN_ALLOWLIST,
  ERROR_CODES,
  FRAME_TYPES,
  LIMITS,
  NET_ERROR_CODES,
  NET_METHODS,
  NET_MUTATING_METHODS,
  NET_RESPONSE_HEADER_WHITELIST,
  PROTOCOL_VERSION,
  SNUG_APP_REQUEST_TAG,
  STRIP_HEADERS,
  classifyErrorCode,
  isKnownErrorCode,
  isWhitelistedNetResponseHeader,
  type FrameType,
  type KnownErrorCode,
  type NetErrorCode,
  type NetMethod,
} from './constants.js';

export {
  APP_KV_TABLE,
  APP_OBJECT_NAME_RULE,
  APP_RESERVED_PREFIXES,
  APP_REST_PREFIX,
  APP_REST_SEPARATOR,
  STANDARD_APP_DOC_SLUGS,
  USERDB_DDL,
  USERDB_FILE,
  USERDB_INDEX_DDL,
  USERDB_LIMITS,
  USERDB_OPFS_DIR,
  USERDB_SCHEMA_VERSION,
  USERDB_TABLES,
  appDataToken,
  appRestTableName,
  isValidAppObjectName,
  type AppSchemaJson,
  type AppSchemaObject,
  type UserDbTable,
} from './userdb-schema.js';

export {
  AUTH_KINDS,
  AUTH_SECRET_PREFIX,
  AUTH_SPEC_STATUS,
  AUTH_SPEC_STATUSES,
  apiKeySchema,
  authFieldSchema,
  authProviderInfoSchema,
  authRegistrationSchema,
  authRequestSchema,
  authSpecSchema,
  basicAuthSchema,
  bearerTokenSchema,
  deriveAuthAllowedHosts,
  getAuthUserLayer,
  hostSetEquals,
  isAuthSpecUnknownKeysOnlyFailure,
  isOrgEligibleAuthSpec,
  normalizeAuthHost,
  authSpecHintsSchema,
  oauth2AuthCodeSchema,
  oauth2ClientCredsSchema,
  resolveAuthCodeLayer,
  type ApiKeySpec,
  type AuthField,
  type AuthFieldType,
  type AuthKind,
  type AuthProviderInfo,
  type AuthRegistration,
  type AuthRequest,
  type AuthSpec,
  type AuthSpecHints,
  type AuthSpecStatus,
  type BasicAuthSpec,
  type BearerTokenSpec,
  type Oauth2AuthCodeSpec,
  type Oauth2ClientCredsSpec,
  type OrgEligibleAuthSpec,
} from './auth-schema.js';

export {
  appAnnounceSchema,
  appCancelSchema,
  appEventSchema,
  appMessageSchema,
  appResponseSchema,
  createResponder,
  dbRequestSchema,
  dbResponseSchema,
  frameWithinLimits,
  hostEventSchema,
  hostReadySchema,
  netRequestSchema,
  netResponseSchema,
  parseFrame,
  respondTo,
  responseErrorSchema,
  type AppAnnounceFrame,
  type AppCancelFrame,
  type AppEventFrame,
  type AppMessageFrame,
  type AppResponseFrame,
  type DbRequestFrame,
  type DbResponseFrame,
  type Frame,
  type FrameParseResult,
  type HostEventFrame,
  type HostReadyFrame,
  type NetRequestFrame,
  type NetResponseFrame,
  type Responder,
  type ResponseError,
} from './frames.js';

export {
  appRequestEnvelopeSchema,
  buildAppRequest,
  isAppRequest,
  parseAppRequest,
  type AppRequestEnvelope,
  type AppRequestParseResult,
  type EnvelopeInput,
} from './envelope.js';

export { parseAgentReply, type AgentReplyResult } from './reply.js';

export {
  AUTH_EVIDENCE_MAX_CHARS,
  AUTH_EVIDENCE_MAX_ITEMS,
  AUTH_PROVENANCES,
  AUTH_WIZARD_DIRECTIVE_KIND,
  authRequiredPayloadSchema,
  authWizardDirectiveSchema,
  inferrerProposalSchema,
  llmProposalSchema,
  renderDirectiveSchema,
  type AuthProvenance,
  type AuthRequiredPayload,
  type AuthWizardDirective,
  type InferrerProposal,
  type LlmProposal,
  type RenderDirective,
} from './render-directive.js';

export {
  scanForCredentialValues,
  stripCredentialHeaders,
  type CredentialFinding,
  type CredentialScan,
} from './security.js';

export { buildJsonSchemas } from './json-schemas.js';
