// @snugprotocol/protocol — the Snug envelope protocol: zod schemas, typed helpers,
// and the single home of every wire constant. Source of truth for snugprotocol/spec
// (see docs/engineering/SPEC_SYNC.md). Browser-safe; runtime dependency: zod only.

export {
  CDN_ALLOWLIST,
  ERROR_CODES,
  FRAME_TYPES,
  LIMITS,
  NET_ERROR_CODES,
  NET_METHODS,
  NET_MUTATING_METHODS,
  NET_RESPONSE_HEADER_WHITELIST,
  PROTOCOL_VERSION,
  SNUG_APP_REQUEST_TAG,
  STRIP_HEADERS,
  classifyErrorCode,
  isKnownErrorCode,
  isWhitelistedNetResponseHeader,
  type FrameType,
  type KnownErrorCode,
  type NetErrorCode,
  type NetMethod,
} from './constants.js';

export {
  APP_KV_TABLE,
  APP_OBJECT_NAME_RULE,
  APP_RESERVED_PREFIXES,
  APP_REST_PREFIX,
  APP_REST_SEPARATOR,
  CONTAINER,
  STANDARD_APP_DOC_SLUGS,
  USERDB_DDL,
  USERDB_EXTENSION,
  USERDB_FILE,
  USERDB_LEGACY_EXTENSION,
  USERDB_LEGACY_FILE,
  USERDB_INDEX_DDL,
  USERDB_LIMITS,
  USERDB_OPFS_DIR,
  USERDB_CONNECTIONS_TABLE,
  USERDB_SCHEMA_VERSION,
  USERDB_TABLES,
  appDataToken,
  appRestTableName,
  isValidAppObjectName,
  type AppSchemaJson,
  type AppSchemaObject,
  type UserDbTable,
} from './userdb-schema.js';

export {
  AUTH_KINDS,
  AUTH_SECRET_PREFIX,
  AUTH_SPEC_STATUS,
  AUTH_SPEC_STATUSES,
  apiKeySchema,
  authFieldSchema,
  authProviderInfoSchema,
  authRegistrationSchema,
  authRequestSchema,
  authSpecSchema,
  basicAuthSchema,
  bearerTokenSchema,
  deriveAuthAllowedHosts,
  getAuthUserLayer,
  hostSetEquals,
  isAuthSpecUnknownKeysOnlyFailure,
  isOrgEligibleAuthSpec,
  normalizeAuthHost,
  authSpecHintsSchema,
  oauth2AuthCodeSchema,
  oauth2ClientCredsSchema,
  resolveAuthCodeLayer,
  type ApiKeySpec,
  type AuthField,
  type AuthFieldType,
  type AuthKind,
  type AuthProviderInfo,
  type AuthRegistration,
  type AuthRequest,
  type AuthSpec,
  type AuthSpecHints,
  type AuthSpecStatus,
  type BasicAuthSpec,
  type BearerTokenSpec,
  type Oauth2AuthCodeSpec,
  type Oauth2ClientCredsSpec,
  type OrgEligibleAuthSpec,
} from './auth-schema.js';

export {
  accessRequestSchema,
  accessResponseSchema,
  appAnnounceSchema,
  appCancelSchema,
  appEventSchema,
  appMessageSchema,
  appResponseSchema,
  createResponder,
  dbRequestSchema,
  dbResponseSchema,
  frameWithinLimits,
  hostEventSchema,
  hostReadySchema,
  netRequestSchema,
  netResponseSchema,
  openUrlRequestSchema,
  openUrlResultSchema,
  parseFrame,
  respondTo,
  responseErrorSchema,
  type AccessRequestFrame,
  type AccessResponseFrame,
  type AppAnnounceFrame,
  type AppCancelFrame,
  type AppEventFrame,
  type AppMessageFrame,
  type AppResponseFrame,
  type DbRequestFrame,
  type DbResponseFrame,
  type Frame,
  type FrameParseResult,
  type HostEventFrame,
  type HostReadyFrame,
  type NetRequestFrame,
  type NetResponseFrame,
  type OpenUrlRequestFrame,
  type OpenUrlResultFrame,
  type Responder,
  type ResponseError,
} from './frames.js';

export {
  appRequestEnvelopeSchema,
  buildAppRequest,
  isAppRequest,
  parseAppRequest,
  type AppRequestEnvelope,
  type AppRequestParseResult,
  type EnvelopeInput,
} from './envelope.js';

export { parseAgentReply, type AgentReplyResult } from './reply.js';

export {
  AUTH_EVIDENCE_MAX_CHARS,
  AUTH_EVIDENCE_MAX_ITEMS,
  AUTH_PROVENANCES,
  AUTH_WIZARD_DIRECTIVE_KIND,
  CONNECTION_REQUIREMENT_DIRECTIVE_KIND,
  authWizardDirectiveSchema,
  connectionRequirementDirectiveSchema,
  inferrerProposalSchema,
  renderDirectiveSchema,
  type AuthProvenance,
  type AuthWizardDirective,
  type ConnectionRequirementDirective,
  type InferrerProposal,
  type RenderDirective,
} from './render-directive.js';

// Dynamic Auth v2 (TASK-20260810 P0) — the requirement contract. ADDITIVE: the v3
// `auth-schema.ts` surface above keeps shipping until P3/P4 rewire its last consumers.
export {
  AUTH_MAX_SLOTS_PER_APP,
  CONNECTION_FIELD_DESCRIPTION_MAX_CHARS,
  CONNECTION_FIELD_KEY_RULE,
  CONNECTION_FIELD_LABEL_MAX_CHARS,
  CONNECTION_FIELD_PLACEHOLDER_MAX_CHARS,
  CONNECTION_HEADER_NAME_RULE,
  CONNECTION_HOST_RULE,
  CONNECTION_KINDS,
  CONNECTION_LAN_HOST_CLASSES,
  CONNECTION_PROVENANCES,
  CONNECTION_QUERY_NAME_RULE,
  CONNECTION_REQUIREMENT_HEADER_VALUE_MAX_CHARS,
  CONNECTION_REQUIREMENT_INSTRUCTION_MAX_CHARS,
  CONNECTION_REQUIREMENT_MAX_FIELDS,
  CONNECTION_REQUIREMENT_MAX_HEADER_ENTRIES,
  CONNECTION_REQUIREMENT_MAX_INSTRUCTIONS,
  CONNECTION_REQUIREMENT_MAX_QUERY_ENTRIES,
  CONNECTION_REQUIREMENT_URL_MAX_CHARS,
  CONNECTION_SLOT_RULE,
  CONNECTION_STATUS,
  CONNECTION_STATUSES,
  CONNECTION_TEST_REQUEST_PATH_MAX_CHARS,
  connectionFieldSchema,
  connectionLanHostSchema,
  connectionProviderSchema,
  connectionRegistrationSchema,
  connectionRequestSchema,
  connectionRequirementSchema,
  connectionTestRequestSchema,
  canonicalRequirementHash,
  deriveConnectionAllowedHosts,
  isRfc1918Ipv4Literal,
  type ConnectionField,
  type ConnectionKind,
  type ConnectionLanHost,
  type ConnectionLanHostClass,
  type ConnectionProvenance,
  type ConnectionProvider,
  type ConnectionRegistration,
  type ConnectionRequest,
  type ConnectionRequirement,
  type ConnectionStatus,
  type ConnectionTestRequest,
} from './connection-requirement.js';

// Lean runtime turns (TASK-20260811 P0, ADR-0018) — the compact artifact a runtime app
// turn assembles FROM. Internal draft: host-assigned at both call sites, never app-claimed,
// and OUT of the json-schemas SOURCES until a spec push is authorized.
export {
  RUNTIME_CONTRACT_MAX_BYTES,
  RUNTIME_CONTRACT_MAX_SETTINGS,
  RUNTIME_CONTRACT_OVERVIEW_MAX_CHARS,
  RUNTIME_CONTRACT_PERSONA_MAX_CHARS,
  RUNTIME_CONTRACT_RESPONSE_GUIDANCE_MAX_CHARS,
  RUNTIME_CONTRACT_SETTING_KEY_RULE,
  RUNTIME_CONTRACT_SETTING_VALUE_MAX_CHARS,
  RUNTIME_CONTRACT_STATE_GUIDANCE_MAX_CHARS,
  RUNTIME_MAX_OUTPUT_TOKENS_CEILING,
  RUNTIME_MAX_OUTPUT_TOKENS_FLOOR,
  canonicalRuntimeContract,
  parseRuntimeContract,
  runtimeContractSchema,
  type RuntimeContract,
} from './runtime-contract.js';

// Intent-routed app chat (TASK-20260811 P0, ADR-0019; provider lane + exhaustive lane
// map TASK-20260815, ADR-0031) — the router's input contract.
export {
  CHAT_INTENTS,
  CHAT_INTENT_CLARIFICATION_MAX_CHARS,
  CHAT_INTENT_DATA_LANE,
  CHAT_INTENT_FEATURE_LANE,
  CHAT_INTENT_PROVIDER_LANE,
  CHAT_INTENT_SCHEDULE_LANE,
  CHAT_LANES,
  LANE_FOR_INTENT,
  chatIntentSchema,
  isDataIntent,
  isFeatureIntent,
  isProviderIntent,
  isScheduleIntent,
  laneForIntent,
  parseChatIntent,
  type ChatIntent,
  type ChatIntentClassification,
  type ChatLane,
} from './chat-intent.js';

export {
  isCredentialKeyName,
  scanForCredentialValues,
  stripCredentialHeaders,
  type CredentialFinding,
  type CredentialScan,
} from './security.js';

// App bundle (TASK-20260904-app-sharing, ADR-0063) — the portable-starter format. Internal
// draft, OUT of the json-schemas SOURCES; the receiver validates at this boundary (C5).
export {
  APP_BUNDLE_DDL_STATEMENT_RULE,
  APP_BUNDLE_DOC_SLUG_RULE,
  APP_BUNDLE_FORMAT,
  APP_BUNDLE_LINEAGE_RULE,
  APP_BUNDLE_MAX_BYTES,
  APP_BUNDLE_MAX_DDL_STATEMENTS,
  APP_BUNDLE_MAX_DDL_STATEMENT_CHARS,
  APP_BUNDLE_MAX_DOCS,
  APP_BUNDLE_MAX_DOC_CONTENT_CHARS,
  APP_BUNDLE_MAX_DOC_TITLE_CHARS,
  APP_BUNDLE_MAX_HTML_CHARS,
  APP_BUNDLE_MAX_HUB_VERSION_CHARS,
  appBundleId,
  appBundleSchema,
  canonicalAppBundleJson,
  isStructureOnlyDdl,
  parseAppBundle,
  type AppBundle,
  type AppBundleDoc,
  type AppBundleParse,
} from './app-bundle.js';

// Scheduled tasks (TASK-20261009-scheduling-framework, ADR-0074) — a task, its steps, a
// run, the scheduler's state and a proposal, as the user's file persists them. Internal
// draft, OUT of the json-schemas SOURCES: scheduling is a host feature, not protocol.
export {
  ALERT_KINDS,
  MISSED_POLICIES,
  PAUSED_REASONS,
  RUN_STATUSES,
  RUN_TRIGGERS,
  SCHEDULED_TASK_MAX_BYTES,
  SCHEDULE_APP_INPUT_MAX_BYTES,
  SCHEDULE_CONTEXT_DEFAULT_ROWS,
  SCHEDULE_CONTEXT_MAX_ROWS,
  SCHEDULE_CONTEXT_SQL_MAX_CHARS,
  SCHEDULE_CONTEXT_SQL_MAX_STATEMENTS,
  SCHEDULE_CRON_MAX_CHARS,
  SCHEDULE_DAILY_CEILINGS,
  SCHEDULE_EVERY_MAX_N,
  SCHEDULE_GRACE_MS,
  SCHEDULE_HOST_KINDS,
  SCHEDULE_ID_MAX_CHARS,
  SCHEDULE_MAX_APP_VERSIONS,
  SCHEDULE_MAX_STEPS,
  SCHEDULE_MAX_TASKS,
  SCHEDULE_MIN_INTERVAL_MS,
  SCHEDULE_NOTIFY_BODY_MAX_CHARS,
  SCHEDULE_PROMPT_MAX_CHARS,
  SCHEDULE_PROPOSALS_PER_RUN,
  SCHEDULE_PROPOSAL_SQL_MAX_CHARS,
  SCHEDULE_PROPOSAL_SUMMARY_MAX_CHARS,
  SCHEDULE_PROPOSAL_TTL_MS,
  SCHEDULE_RUNS_MAX_BYTES,
  SCHEDULE_RUNS_MAX_ENTRIES,
  SCHEDULE_RUNS_TOTAL_MAX_BYTES,
  SCHEDULE_RUN_MAX_BYTES,
  SCHEDULE_RUN_REASON_MAX_CHARS,
  SCHEDULE_STALE_AFTER_MS,
  SCHEDULE_STEP_SUMMARY_MAX_CHARS,
  SCHEDULE_TITLE_MAX_CHARS,
  SCHEDULE_TZ_MAX_CHARS,
  SCHEDULE_UNITS,
  SCHEDULE_UNTIL_MAX_COUNT,
  STEP_RESULT_STATUSES,
  TASK_PROVENANCES,
  WEEKDAYS,
  canonicalScheduleIntent,
  canonicalScheduledTask,
  findScheduleCredential,
  isIanaTimeZone,
  isReadOnlySelect,
  isSingleDmlStatement,
  parseScheduleProposal,
  parseScheduleRun,
  parseScheduledTask,
  parseSchedulerState,
  proposalHash,
  scheduleProposalItemSchema,
  scheduleProposalSchema,
  scheduleRunSchema,
  scheduleSpecSchema,
  scheduleStepSchema,
  scheduledTaskSchema,
  schedulerStateSchema,
  stepResultSchema,
  type AlertKind,
  type MissedPolicy,
  type PausedReason,
  type RunStatus,
  type RunTrigger,
  type ScheduleCredentialIssue,
  type ScheduleHostKind,
  type ScheduleProposal,
  type ScheduleProposalItem,
  type ScheduleRun,
  type ScheduleSpec,
  type ScheduleStep,
  type ScheduleUnit,
  type ScheduleUntil,
  type ScheduledTask,
  type SchedulerState,
  type StepResult,
  type StepResultStatus,
  type TaskProvenance,
  type Weekday,
} from './schedule.js';

// The guards every persisted record shares (TASK-20261010-cross-app-access D8): the SQL
// statement rules, the ONE credential walk, and the record-identity helpers. `isReadOnlySelect`
// is exported above through schedule.ts's re-export (the same function).
export {
  CTE_WRITE_RULE,
  DML_PREFIX_RULE,
  FORBIDDEN_TOKEN_RULE,
  SELECT_PREFIX_RULE,
  SINGLE_STATEMENT_RULE,
  canonicalJson,
  findRecordCredential,
  fnv1a64Hex,
  utf8ByteLength,
  type RecordCredentialIssue,
} from './record-guards.js';

// Access between apps (TASK-20261010-cross-app-access, ADR-0075; spec 1.1 Part VI). The
// frames (`accessRequestSchema`/`accessResponseSchema`) are PUBLISHED and exported above from
// frames.ts; these are their field-level pieces, Appendix A/B, and the two records (normative
// prose in spec §22 — no JSON Schema, the Part III–V rule).
export {
  ACCESS_APP_ID_MAX_CHARS,
  ACCESS_CHANGED_EVENT,
  ACCESS_COLUMN_NAME_MAX_CHARS,
  ACCESS_DURATIONS,
  ACCESS_ENDED_RETENTION_MS,
  ACCESS_ERROR_CODES,
  ACCESS_GRANT_MAX_BYTES,
  ACCESS_GRANT_STATUSES,
  ACCESS_HINT_TABLES_MAX,
  ACCESS_HINT_WORDS_MAX,
  ACCESS_HINT_WORD_MAX_CHARS,
  ACCESS_LOG_COALESCE_MS,
  ACCESS_LOG_KINDS,
  ACCESS_LOG_MAX_BYTES,
  ACCESS_LOG_MAX_ENTRIES,
  ACCESS_LOG_REASON_MAX_CHARS,
  ACCESS_LOG_SQL_MAX_CHARS,
  ACCESS_LOG_TOTAL_MAX_BYTES,
  ACCESS_MAX_COLUMNS,
  ACCESS_MAX_GRANTS,
  ACCESS_MAX_PARAMS,
  ACCESS_MAX_RESULT_BYTES,
  ACCESS_MAX_ROWS,
  ACCESS_MAX_TABLES,
  ACCESS_OPS,
  ACCESS_PARAM_STRING_MAX_CHARS,
  ACCESS_PROVENANCES,
  ACCESS_PURPOSE_MAX_CHARS,
  ACCESS_QUERY_RATE_PER_MINUTE,
  ACCESS_QUERY_TIMEOUT_MS,
  ACCESS_REQUEST_MIN_GAP_MS,
  ACCESS_SCOPED_CACHE_MS,
  ACCESS_SOURCE_MAX_BYTES,
  ACCESS_SQL_MAX_CHARS,
  ACCESS_SUSPEND_REASONS,
  ACCESS_TIMEOUT_STRIKES,
  accessGrantDurationSchema,
  accessGrantSchema,
  accessGrantViewSchema,
  accessHintWordSchema,
  accessHintsSchema,
  accessLogEntrySchema,
  accessParamSchema,
  accessParamsSchema,
  accessPurposeSchema,
  accessRequestHash,
  accessScopeSchema,
  accessSqlSchema,
  accessTableNameSchema,
  canonicalAccessGrantIntent,
  durationToExpiry,
  isAccessErrorCode,
  parseAccessGrant,
  parseAccessLogEntry,
  type AccessDuration,
  type AccessErrorCode,
  type AccessGrant,
  type AccessGrantDuration,
  type AccessGrantStatus,
  type AccessGrantView,
  type AccessHints,
  type AccessLogEntry,
  type AccessLogKind,
  type AccessOp,
  type AccessParam,
  type AccessProvenance,
  type AccessRequestSemantics,
  type AccessScope,
  type AccessSuspendReason,
} from './access.js';

export { buildJsonSchemas } from './json-schemas.js';
export { CONNECTION_URL_SCHEME, parseConnectionUrl, type ConnectionUrlParse } from './connection-url.js';

// The sidecar HTTP contract (ADR-0032, internal draft — not a published schema). One home
// for literals shared by the Node sidecar, the Rust admission, the wizard and the app.
export {
  APP_REACHABLE_SIDECAR_ROUTES,
  SIDECAR_AUTH_HEADER,
  SIDECAR_ROUTES,
  SIDECAR_SOCKET_BASENAME,
  SIDECAR_SYMBOLIC_HOST,
  isAppReachableSidecarRoute,
  type SidecarMethod,
  type SidecarRoute,
} from './sidecar-contract.js';
