// AC4 — the docs hub's navigation and its pages cannot drift apart.
//
// Two directions: every explicit `slug:` in astro.config.mjs has a content file behind
// it, and every content file under src/content/docs/ was actually built into dist/.
// The spec section is autogenerated from its directory, so the second half is what
// covers it.
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const CONTENT = join(ROOT, 'src', 'content', 'docs');
const DIST = join(ROOT, 'dist');

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path, out);
    else if (/\.(md|mdx)$/.test(name)) out.push(path);
  }
  return out;
}

/** Content file → Starlight route slug (paths are the routing contract). */
function slugFor(file: string): string {
  return relative(CONTENT, file)
    .replace(/\.(md|mdx)$/, '')
    .split(sep)
    .join('/')
    .replace(/\/index$/, '')
    .replace(/^index$/, '');
}

describe('docs nav integrity', () => {
  it('every explicit sidebar slug in astro.config.mjs has a content file', () => {
    const config = readFileSync(join(ROOT, 'astro.config.mjs'), 'utf8');
    const slugs = [...config.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1]);
    expect(slugs.length).toBeGreaterThan(0);
    const missing = slugs.filter(
      (slug) =>
        !existsSync(join(CONTENT, `${slug}.md`)) &&
        !existsSync(join(CONTENT, `${slug}.mdx`)) &&
        !existsSync(join(CONTENT, slug, 'index.md')) &&
        !existsSync(join(CONTENT, slug, 'index.mdx')),
    );
    expect(missing).toEqual([]);
  });

  it('every content page was built into dist', () => {
    const missing = walk(CONTENT)
      .map(slugFor)
      .filter((slug) => !existsSync(join(DIST, slug, 'index.html')));
    expect(missing).toEqual([]);
  });

  it('the hub has pages at all (an empty content tree must not pass)', () => {
    expect(walk(CONTENT).length).toBeGreaterThanOrEqual(10);
  });
});

describe('C4 — nothing in the website references internal/', () => {
  it('no content or source file mentions the internal/ tree', () => {
    // Scoped to SHIPPED content — test files may name the forbidden string as their
    // needle (lessons 2026-08-20: scope a "must not appear" assertion to the construct
    // it governs, or it forbids documenting the thing it forbids).
    const dirs = [join(ROOT, 'src'), join(ROOT, 'scripts')];
    const offenders: string[] = [];
    for (const dir of dirs) {
      for (const name of readdirSync(dir, { recursive: true }) as string[]) {
        const path = join(dir, name);
        if (path.includes('__tests__')) continue;
        if (statSync(path).isDirectory() || !/\.(ts|mts|astro|mdx?|css|mjs|json)$/.test(name))
          continue;
        if (readFileSync(path, 'utf8').includes('internal/')) offenders.push(path);
      }
    }
    expect(offenders).toEqual([]);
  });
});
