// AC4 — the docs hub's navigation and its pages cannot drift apart.
//
// Two directions: every explicit `slug:` in astro.config.mjs has a content file behind
// it, and every content file under src/content/docs/ was actually built into dist/.
// The spec section is autogenerated from its directory, so the second half is what
// covers it.
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const CONTENT = join(ROOT, 'src', 'content', 'docs');
const DIST = join(ROOT, 'dist');

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path, out);
    else if (/\.(md|mdx)$/.test(name)) out.push(path);
  }
  return out;
}

/** Content file → Starlight route slug (paths are the routing contract). */
function slugFor(file: string): string {
  return relative(CONTENT, file)
    .replace(/\.(md|mdx)$/, '')
    .split(sep)
    .join('/')
    .replace(/\/index$/, '')
    .replace(/^index$/, '');
}

describe('docs nav integrity', () => {
  it('every explicit sidebar slug in astro.config.mjs has a content file', () => {
    const config = readFileSync(join(ROOT, 'astro.config.mjs'), 'utf8');
    const slugs = [...config.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1]);
    expect(slugs.length).toBeGreaterThan(0);
    const missing = slugs.filter(
      (slug) =>
        !existsSync(join(CONTENT, `${slug}.md`)) &&
        !existsSync(join(CONTENT, `${slug}.mdx`)) &&
        !existsSync(join(CONTENT, slug, 'index.md')) &&
        !existsSync(join(CONTENT, slug, 'index.mdx')),
    );
    expect(missing).toEqual([]);
  });

  it('every content page was built into dist', () => {
    const missing = walk(CONTENT)
      .map(slugFor)
      .filter((slug) => !existsSync(join(DIST, slug, 'index.html')));
    expect(missing).toEqual([]);
  });

  it('the hub has pages at all (an empty content tree must not pass)', () => {
    expect(walk(CONTENT).length).toBeGreaterThanOrEqual(10);
  });

  // TASK-20260821-site-playground-polish AC4 — the two checks above validate against
  // DISK, which stayed green while the dev server threw `The slug "docs" ... does not
  // exist`: a half-written .astro/ content store (interrupted sync) had dropped every
  // .mdx entry, and a STALE dist/ from an older successful build masked it here. A
  // corrupt store makes `astro build` itself fail, so the class only survives behind
  // a stale dist — these close that mask.
  it('every explicit sidebar slug was actually built into dist', () => {
    const config = readFileSync(join(ROOT, 'astro.config.mjs'), 'utf8');
    const slugs = [...config.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1]);
    const missing = slugs.filter((slug) => !existsSync(join(DIST, slug, 'index.html')));
    expect(missing, 'sidebar slugs with no built page — rebuild apps/website').toEqual([]);
  });

  it('dist is not older than the content/config sources it was built from', () => {
    const newestSource = [...walk(CONTENT), join(ROOT, 'astro.config.mjs')]
      .map((file) => statSync(file).mtimeMs)
      .reduce((a, b) => Math.max(a, b), 0);
    const distIndex = join(DIST, 'index.html');
    expect(existsSync(distIndex), 'dist/index.html missing — build apps/website first').toBe(true);
    expect(
      statSync(distIndex).mtimeMs >= newestSource,
      'dist/ is older than src/content or astro.config.mjs — rebuild apps/website ' +
        '(if the build errors on a slug whose file exists, delete apps/website/.astro ' +
        'and rebuild: an interrupted content sync leaves a half-written store)',
    ).toBe(true);
  });
});

describe('C4 — nothing in the website references internal/', () => {
  it('no content or source file mentions the internal/ tree', () => {
    // Scoped to SHIPPED content — test files may name the forbidden string as their
    // needle (lessons 2026-08-20: scope a "must not appear" assertion to the construct
    // it governs, or it forbids documenting the thing it forbids).
    const dirs = [join(ROOT, 'src'), join(ROOT, 'scripts')];
    const offenders: string[] = [];
    for (const dir of dirs) {
      for (const name of readdirSync(dir, { recursive: true }) as string[]) {
        const path = join(dir, name);
        if (path.includes('__tests__')) continue;
        if (statSync(path).isDirectory() || !/\.(ts|mts|astro|mdx?|css|mjs|json)$/.test(name))
          continue;
        if (readFileSync(path, 'utf8').includes('internal/')) offenders.push(path);
      }
    }
    expect(offenders).toEqual([]);
  });
});
