// terms.ts — the terms of use (ADR-0055 §1/§6/§7/§8; TASK-20260823-legal-terms-privacy-eula).
//
// Disclosure first, contract second: these terms are footer-linked and never a gate
// (Berman v. Freedom Financial — a browsewrap binds nobody, and we do not pretend it
// does). Their job is to be TRUE about the software and to state, in swappable
// paragraphs, the few things a free MIT project maintained by one person needs said:
// MIT governs the code and wins on any conflict about rights in it; the software is
// as-is; nothing is held so nothing is recoverable; a narrow, enumerated indemnity for
// the third-party-claim paths the user alone creates (R-9/R-10); a liability cap with
// the California Civil Code §1668 carve-out so the clause survives with a hole instead
// of dying whole; no age gate (Kid Mode is a shipping goal); California law and venue.
//
// NOT LEGAL ADVICE — drafted from the codebase's disclosed facts and the owner's
// spec; counsel review before flip-public is the owner's standing item. Each clause is
// self-contained so any one can be replaced without touching the others.

import {
  APP_DISTRIBUTOR,
  GOVERNING_LAW,
  LEGAL_CONTACT,
  LEGAL_UPDATED,
  LICENSE_URL,
  MIT_DISCLAIMER,
  PRIVACY_PATH,
  SECURITY_POLICY_URL,
  SITE_OPERATOR,
  SITE_OPERATOR_DESCRIBED,
  TERMS_PATH,
  THREAT_MODEL_URL,
  UPDATE_CHECK_PAIRING,
  VENUE,
  WE_US_OUR_DEFINITION,
  link,
  list,
  p,
  quote,
  type LegalDocument,
} from './legalShared.js';

export const TERMS: LegalDocument = {
  slug: 'terms',
  title: 'Terms of use',
  updated: LEGAL_UPDATED,
  intro: [
    `These terms cover the Snug website and hosted Playground, which are operated by ${SITE_OPERATOR_DESCRIBED}, and the Snug desktop application for macOS, which is distributed by ${APP_DISTRIBUTOR}. The Snug source code is copyright ${APP_DISTRIBUTOR} and Snug Protocol contributors and is licensed to everyone under the MIT License. `,
    WE_US_OUR_DEFINITION,
    ' By using the site, the Playground or the app you are using free, pre-release software on the basis set out here.',
  ],
  sections: [
    {
      id: 'the-software',
      heading: 'The software and the license',
      blocks: [
        p(
          'Snug is free software under the ',
          link(LICENSE_URL, 'MIT License'),
          '. The MIT License governs your rights in the code — to use, copy, modify, distribute and sell it — and if anything in these terms conflicts with the MIT License about rights in the code, the MIT License wins. These terms add only what the license does not address: the hosted site and Playground that ',
          SITE_OPERATOR,
          ' runs, the desktop application that ',
          APP_DISTRIBUTOR,
          ' distributes, and the relationship between you and us when you use them.',
        ),
        p(
          'Nothing is sold here. There is no account, no subscription, no payment and no plan. Where Snug connects to a model provider or another service, you bring your own key or account and pay that provider directly under their terms.',
        ),
      ],
    },
    {
      id: 'pre-release',
      heading: 'Pre-release software',
      blocks: [
        p(
          'Snug is pre-1.0. It may change without notice, break, lose a feature, or stop being offered. The hosted Playground may go away or move. We will say so in release notes when we can, but you should not build anything on the assumption that today\'s behaviour is tomorrow\'s.',
        ),
      ],
    },
    {
      id: 'your-data',
      heading: 'Your data and your backups',
      blocks: [
        p(
          'Everything Snug knows lives in one file that is yours, on your device or in storage you chose. We hold no copy. That means we cannot recover, restore, reset or hand back anything: if the file is lost, corrupted, deleted, or encrypted with a passphrase only you hold and a Recovery Key you no longer have, the data is unrecoverable and there is nothing we can do. Backups are your job — the export button in Settings exists for exactly that.',
        ),
        p('The ', link(PRIVACY_PATH, 'privacy statement'), ' says what can leave your device, to whom, and when.'),
      ],
    },
    {
      id: 'your-apps',
      heading: 'Your apps and the services you connect',
      blocks: [
        p(
          'Apps you build with Snug are yours. They are also your responsibility: an app generated by a model can be wrong, and an app you share or publish is something you chose to give someone else. Review what an app does before you approve a connection for it, and before you let it act on a real account.',
        ),
        p(
          'Every service you connect — a model provider, an API, a device on your network, a messaging account — is governed by that service\'s own terms, not ours. Some of those terms forbid what Snug makes possible: in particular, linking an automation tool to a personal WhatsApp account is against WhatsApp\'s terms and accounts have been banned for it. The screen where you link says so; the choice, and its consequences, are yours.',
        ),
        p(
          'The keys and tokens you save are yours to keep safe. Snug keeps them in your file, injects them only at the boundary the threat model describes, and never shows them to an app or a model — but a key you paste into the wrong place, export with secrets included, or sync to storage someone else can reach is a key you have shared.',
        ),
      ],
    },
    {
      id: 'acceptable-use',
      heading: 'Acceptable use',
      blocks: [
        p(
          'Use Snug lawfully and do not use it to harm other people: do not use it to access systems or accounts you are not entitled to, to harass, to spam, or to collect other people\'s data in ways they would object to and the law forbids. Do not try to break the sandbox or the credential boundary in someone else\'s running copy.',
        ),
        p(
          'Security research on your own copy is welcome and authorised under the safe-harbour terms in our ',
          link(SECURITY_POLICY_URL, 'security policy'),
          ', which also says how to report what you find.',
        ),
      ],
    },
    {
      id: 'children',
      heading: 'Children',
      blocks: [
        p(
          'Snug has no accounts and collects nothing, so there is no profile of a child for us to hold. Because the software can connect to real accounts and sends text to a model provider, we ask that a parent or guardian set it up for a child and stay involved in what it is connected to. A child building an app with a parent nearby is one of the things Snug is for.',
        ),
      ],
    },
    {
      id: 'no-warranty',
      heading: 'No warranty',
      blocks: [
        p('The software is provided under the MIT License, whose disclaimer applies in full and reads:'),
        quote(MIT_DISCLAIMER),
        p(
          'That disclaimer covers security too. Snug\'s security claims, and the ones it deliberately does not make, are written in the ',
          link(THREAT_MODEL_URL, 'threat model'),
          ' — see in particular its section "What this model does not claim". We give no warranty that the software is secure, that any sandbox or credential boundary cannot be defeated, or that a model will behave. The hosted site and Playground are provided on the same as-is basis.',
        ),
      ],
    },
    {
      id: 'liability',
      heading: 'Limitation of liability',
      blocks: [
        p(
          'To the maximum extent permitted by law, we are not liable to you for any indirect, incidental, special, consequential or punitive damages, or for any loss of data, profits, or use, arising out of or in connection with Snug, the site, the Playground or the app — and our total liability to you for all claims together is limited to USD 50.',
        ),
        p(
          'This limit does not apply where the law does not allow it. In particular, under California Civil Code section 1668 nothing here limits liability for fraud, for willful injury to a person or property, or for a violation of law, and nothing here limits liability for gross negligence.',
        ),
        p(
          'The figure is not a discount on something you bought — you bought nothing. It is a plain statement that a free, MIT-licensed project maintained by one person cannot carry open-ended financial risk, and that by using it you are choosing to use it on that basis.',
        ),
      ],
    },
    {
      id: 'indemnity',
      heading: 'What you take responsibility for',
      blocks: [
        p(
          'You agree to defend and hold us harmless from claims by other people, and the reasonable costs of them, to the extent they arise from exactly these four things:',
        ),
        list(
          ['apps you created, shared or published with Snug;'],
          ['your use of a third-party service, account or credential through Snug;'],
          ['your breach of a third party\'s terms;'],
          ['your breach of these terms, or your violation of law.'],
        ),
        p('That is the whole of it. This is not a general indemnity, and it does not cover anything we did.'),
      ],
    },
    {
      id: 'updates',
      heading: 'Updates',
      blocks: [
        p(
          `The desktop app checks for new versions and offers them. ${UPDATE_CHECK_PAIRING} The installer for the desktop app shows a short license screen; the terms it summarises are these.`,
        ),
      ],
    },
    {
      id: 'changes',
      heading: 'Changes to these terms',
      blocks: [
        p(
          `These terms are dated ${LEGAL_UPDATED} and live at ${TERMS_PATH} on the Playground and on snugprotocol.org. When they change, the date changes and the release notes say what moved. Continuing to use the site, the Playground or the app after a change means using them under the changed terms.`,
        ),
      ],
    },
    {
      id: 'termination',
      heading: 'Ending this',
      blocks: [
        p(
          'You can stop at any time: delete the app, delete your file, close the tab. Because we hold nothing, there is nothing on our side to close. We may stop offering the hosted site, the Playground or the desktop download at any time; the MIT License on the code is perpetual and unaffected.',
        ),
      ],
    },
    {
      id: 'law',
      heading: 'Law and venue',
      blocks: [
        p(
          `These terms are governed by ${GOVERNING_LAW}, without regard to its conflict-of-laws rules. Any dispute that cannot be resolved by talking to us first will be brought in ${VENUE}, and you and we each consent to that venue. If any part of these terms is found unenforceable, the rest stands.`,
        ),
      ],
    },
    {
      id: 'contact',
      heading: 'Contact',
      blocks: [p(`Questions about these terms: ${LEGAL_CONTACT}. Security reports: see the security policy linked above.`)],
    },
  ],
};
