// TASK-20260812-desktop-auth-awareness P3-executor (ADR-0022 §2) — the `cdp_jwt`
// template helper, written RED-FIRST at Gate 3 against an engine that does not know the
// name yet.
//
// WHAT IT MINTS. `{{cdp_jwt(api_key, private_key)}}` renders a fresh ES256 CDP JWT per
// render pass: protected header { alg:'ES256', kid:<api_key value>, typ:'JWT',
// nonce:<16-byte hex> }, payload { iss:'cdp', sub:<api_key value>,
// uri:'<METHOD> <host><path>' (NO scheme, NO query — pinned below), nbf:now,
// exp:now+120 }. WebCrypto ECDSA P-256 only at v1; the raw r||s signature IS the JWS
// ES256 format (no DER conversion — probe-verified at P0, amendment 4).
//
// THE VERIFICATION IS INDEPENDENT (AC4). The signature is checked with
// `crypto.subtle.verify` against the PUBLIC key derived (by openssl, offline) from the
// checked-in fixture private key — never by re-running the helper and comparing it to
// itself (lesson 2026-08-11: a guard that compares two values computed by the same
// function verifies agreement, not correctness).
//
// FIXTURE KEYS ARE TEST KEYS. `fixtures/cdp-test-key.*` were generated by openssl for
// this suite and appear in no provider account; committing them is the point — the
// SEC1 header (`BEGIN EC PRIVATE KEY`) is the exact shape the CDP portal downloads
// (amendment 4), so the import path is exercised against the real format, not a
// hand-simplified one. No real secret appears in this file (C1).

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { AuthTemplateError, renderAuthHeaderTemplate, renderAuthTemplateString } from '../template-engine.js';

const fixturesDir = join(__dirname, 'fixtures');
const SEC1_PEM = readFileSync(join(fixturesDir, 'cdp-test-key.sec1.pem'), 'utf8');
const PKCS8_PEM = readFileSync(join(fixturesDir, 'cdp-test-key.pkcs8.pem'), 'utf8');
const PUBLIC_PEM = readFileSync(join(fixturesDir, 'cdp-test-key.pub.pem'), 'utf8');
const ED25519_PEM = readFileSync(join(fixturesDir, 'ed25519-test-key.pkcs8.pem'), 'utf8');

/** The CDP key NAME — the non-secret identifier that rides kid/sub. */
const KEY_NAME = 'organizations/11111111-2222-3333-4444-555555555555/apiKeys/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';

const DECLARED = ['api_key', 'private_key'] as const;

const TEMPLATE = { Authorization: 'Bearer {{cdp_jwt(api_key, private_key)}}' };

function ctxWith(privateKey: string, request?: { method: string; url: string; body?: string }) {
  return {
    fields: { api_key: KEY_NAME, private_key: privateKey },
    declaredFieldKeys: [...DECLARED],
    ...(request !== undefined ? { request } : {}),
  };
}

const ACCOUNTS_REQUEST = { method: 'GET', url: 'https://api.coinbase.com/api/v3/brokerage/accounts' };

const b64urlToBytes = (segment: string): Uint8Array => new Uint8Array(Buffer.from(segment, 'base64url'));
const b64urlToJson = (segment: string): Record<string, unknown> =>
  JSON.parse(Buffer.from(segment, 'base64url').toString('utf8')) as Record<string, unknown>;

async function renderJwt(privateKey: string, request = ACCOUNTS_REQUEST): Promise<string> {
  const headers = await renderAuthHeaderTemplate({ ...TEMPLATE }, ctxWith(privateKey, request));
  const value = headers['Authorization']!;
  expect(value.startsWith('Bearer ')).toBe(true);
  return value.slice('Bearer '.length);
}

async function importPublicKey(): Promise<CryptoKey> {
  const body = PUBLIC_PEM.replace('-----BEGIN PUBLIC KEY-----', '')
    .replace('-----END PUBLIC KEY-----', '')
    .replace(/\s+/g, '');
  const spki = new Uint8Array(Buffer.from(body, 'base64'));
  return crypto.subtle.importKey('spki', spki as BufferSource, { name: 'ECDSA', namedCurve: 'P-256' }, false, [
    'verify',
  ]);
}

async function verifyJwt(jwt: string): Promise<boolean> {
  const [headerSeg, payloadSeg, sigSeg] = jwt.split('.');
  const publicKey = await importPublicKey();
  const signingInput = new TextEncoder().encode(`${headerSeg}.${payloadSeg}`);
  const signature = b64urlToBytes(sigSeg!);
  expect(signature.byteLength, 'ES256 JWS signature is raw r||s — exactly 64 bytes').toBe(64);
  return crypto.subtle.verify(
    { name: 'ECDSA', hash: 'SHA-256' },
    publicKey,
    signature as BufferSource,
    signingInput as BufferSource,
  );
}

afterEach(() => {
  vi.unstubAllGlobals();
});

// ---------------------------------------------------------------------------
// AC4 — independent decode + ES256 verify against the fixture public key
// ---------------------------------------------------------------------------

describe('AC4 — cdp_jwt mints a verifiable ES256 CDP JWT (SEC1 fixture key)', () => {
  it('renders three base64url segments, no padding', async () => {
    const jwt = await renderJwt(SEC1_PEM);
    const segments = jwt.split('.');
    expect(segments).toHaveLength(3);
    for (const segment of segments) {
      expect(segment).toMatch(/^[A-Za-z0-9_-]+$/); // url-safe alphabet, unpadded
    }
  });

  it('protected header has EXACTLY {alg, kid, typ, nonce} with the pinned values', async () => {
    const jwt = await renderJwt(SEC1_PEM);
    const header = b64urlToJson(jwt.split('.')[0]!);
    expect(Object.keys(header).sort()).toEqual(['alg', 'kid', 'nonce', 'typ']);
    expect(header['alg']).toBe('ES256');
    expect(header['typ']).toBe('JWT');
    expect(header['kid'], 'kid is the API key NAME — never key material').toBe(KEY_NAME);
    expect(header['nonce'], '16 random bytes as lowercase hex').toMatch(/^[0-9a-f]{32}$/);
  });

  it('payload has EXACTLY {iss, sub, uri, nbf, exp} — iss cdp, sub key name, exp = nbf+120', async () => {
    const before = Math.floor(Date.now() / 1000);
    const jwt = await renderJwt(SEC1_PEM);
    const after = Math.floor(Date.now() / 1000);
    const payload = b64urlToJson(jwt.split('.')[1]!);
    expect(Object.keys(payload).sort()).toEqual(['exp', 'iss', 'nbf', 'sub', 'uri']);
    expect(payload['iss']).toBe('cdp');
    expect(payload['sub']).toBe(KEY_NAME);
    expect(payload['uri']).toBe('GET api.coinbase.com/api/v3/brokerage/accounts');
    const nbf = payload['nbf'] as number;
    expect(nbf).toBeGreaterThanOrEqual(before);
    expect(nbf).toBeLessThanOrEqual(after);
    expect(payload['exp'], 'exp is pinned at nbf + 120 seconds').toBe(nbf + 120);
  });

  it('the signature VERIFIES with WebCrypto against the fixture public key', async () => {
    const jwt = await renderJwt(SEC1_PEM);
    await expect(verifyJwt(jwt)).resolves.toBe(true);
  });

  it('a tampered payload FAILS verification — the verify above is not vacuous', async () => {
    const jwt = await renderJwt(SEC1_PEM);
    const [headerSeg, payloadSeg, sigSeg] = jwt.split('.');
    const payload = b64urlToJson(payloadSeg!);
    payload['uri'] = 'GET evil.example/steal';
    const forged = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64url');
    await expect(verifyJwt(`${headerSeg}.${forged}.${sigSeg}`)).resolves.toBe(false);
  });

  it('uri claim carries METHOD + host + pathname — NO scheme, NO query (pin)', async () => {
    const jwt = await renderJwt(SEC1_PEM, {
      method: 'GET',
      url: 'https://api.coinbase.com/api/v3/brokerage/accounts?limit=5&cursor=abc',
    });
    const payload = b64urlToJson(jwt.split('.')[1]!);
    expect(payload['uri']).toBe('GET api.coinbase.com/api/v3/brokerage/accounts');
    expect(String(payload['uri'])).not.toContain('https');
    expect(String(payload['uri'])).not.toContain('limit');
  });

  it('every render mints a FRESH JWT — nonces differ between two renders', async () => {
    const first = await renderJwt(SEC1_PEM);
    const second = await renderJwt(SEC1_PEM);
    const nonceOf = (jwt: string): unknown => b64urlToJson(jwt.split('.')[0]!)['nonce'];
    expect(nonceOf(first)).not.toBe(nonceOf(second));
  });
});

// ---------------------------------------------------------------------------
// Amendment 4 — key import: both PEM headers, pasted-PEM normalization
// ---------------------------------------------------------------------------

describe('amendment 4 — key import accepts SEC1 and PKCS#8, normalizes pasted PEM', () => {
  it("PKCS#8 'BEGIN PRIVATE KEY' passes through and verifies", async () => {
    const jwt = await renderJwt(PKCS8_PEM);
    await expect(verifyJwt(jwt)).resolves.toBe(true);
  });

  it('a pasted PEM with escaped \\n and stray whitespace normalizes and verifies', async () => {
    // The shape a key takes after riding a JSON string or a form paste: literal
    // backslash-n instead of newlines, plus surrounding whitespace.
    const pasted = `  ${SEC1_PEM.trimEnd().split('\n').join('\\n')}  `;
    const jwt = await renderJwt(pasted);
    await expect(verifyJwt(jwt)).resolves.toBe(true);
  });

  it('an Ed25519 PEM earns the honest error NAMING THE FIX — and never echoes key bytes', async () => {
    const attempt = renderJwt(ED25519_PEM);
    await expect(attempt).rejects.toThrow(AuthTemplateError);
    await expect(attempt).rejects.toThrow(/generate an EC \(ES256\) key in the CDP portal/);
    const err = await renderJwt(ED25519_PEM).catch((e: unknown) => e as Error);
    const keyBody = ED25519_PEM.split('\n')[1]!; // first base64 line of the fixture
    expect((err as Error).message).not.toContain(keyBody);
  });

  it('an undecodable PEM earns a clear typed error that never echoes the pasted content', async () => {
    const attempt = renderJwt('definitely-not-a-pem-3f9a');
    await expect(attempt).rejects.toThrow(AuthTemplateError);
    const err = await renderJwt('definitely-not-a-pem-3f9a').catch((e: unknown) => e as Error);
    expect((err as Error).message).not.toContain('definitely-not-a-pem-3f9a');
    expect((err as Error).message).toMatch(/private key/i);
  });

  it('a garbled base64 body under a valid SEC1 header errors honestly, no key echo', async () => {
    const garbled = '-----BEGIN EC PRIVATE KEY-----\n!!!not-base64!!!\n-----END EC PRIVATE KEY-----';
    await expect(renderJwt(garbled)).rejects.toThrow(AuthTemplateError);
  });
});

// ---------------------------------------------------------------------------
// Amendment 4/9 — no native WebCrypto ECDSA ⇒ honest error, never silence
// ---------------------------------------------------------------------------

describe('amendments 4/9 — a runtime without WebCrypto ECDSA fails LOUDLY', () => {
  it('crypto without subtle → AuthTemplateError naming WebCrypto ECDSA', async () => {
    const realGetRandomValues = crypto.getRandomValues.bind(crypto);
    vi.stubGlobal('crypto', { getRandomValues: realGetRandomValues });
    const attempt = renderAuthHeaderTemplate({ ...TEMPLATE }, ctxWith(SEC1_PEM, ACCOUNTS_REQUEST));
    await expect(attempt).rejects.toThrow(AuthTemplateError);
    await expect(
      renderAuthHeaderTemplate({ ...TEMPLATE }, ctxWith(SEC1_PEM, ACCOUNTS_REQUEST)),
    ).rejects.toThrow(/WebCrypto|ECDSA/);
  });
});

// ---------------------------------------------------------------------------
// The engine's own half of the argument contract (the lint is the other half)
// ---------------------------------------------------------------------------

describe("cdp_jwt engine-half guards (the lint's rules are tested in template-lint.test.ts)", () => {
  it('no request context → honest error (the uri claim cannot be minted)', async () => {
    await expect(renderAuthHeaderTemplate({ ...TEMPLATE }, ctxWith(SEC1_PEM))).rejects.toThrow(
      /request context/i,
    );
  });

  it('wrong arity throws the honest (api_key, private_key) message', async () => {
    // Direct string render — below the lint gate — so this is the ENGINE refusing.
    await expect(
      renderAuthTemplateString('{{cdp_jwt(api_key)}}', ctxWith(SEC1_PEM, ACCOUNTS_REQUEST)),
    ).rejects.toThrow(/cdp_jwt requires \(api_key, private_key\)/);
  });

  it('a BLANK declared private_key field throws honestly instead of signing with nothing', async () => {
    const ctx = {
      fields: { api_key: KEY_NAME },
      declaredFieldKeys: [...DECLARED],
      request: ACCOUNTS_REQUEST,
    };
    await expect(renderAuthTemplateString('{{cdp_jwt(api_key, private_key)}}', ctx)).rejects.toThrow(
      AuthTemplateError,
    );
  });
});
