// astro.config.mjs — the public website: marketing pages + the /docs hub (ADR-0048).
//
// Starlight owns everything under src/content/docs/; the extra `docs/` folder inside it
// is what namespaces the hub under /docs (Starlight derives routes from file paths, so
// content/docs/docs/get-started.md → /docs/get-started). Astro pages (src/pages/) carry
// the marketing surfaces: /, /download.
//
// The `@playground` alias mirrors apps/desktop's: the website consumes playground
// source (releaseChannel.ts constants, theme tokens) read-only — never the reverse
// (ADR-0047 §2 dependency direction).
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { fileURLToPath } from 'node:url';

const playgroundSrc = fileURLToPath(new URL('../playground/src', import.meta.url));

export default defineConfig({
  site: 'https://snugprotocol.org',
  vite: {
    resolve: {
      alias: { '@playground': playgroundSrc },
    },
    // Starlight's Code chunk bundles postcss (CJS), whose interop emits a DEFAULT import
    // of nanoid/non-secure; the workspace resolves nanoid@3 whose ESM build exports only
    // named symbols, so an externalized nanoid crashes static generation. Bundling it
    // keeps the interop internal to rollup, where it is handled correctly.
    ssr: { noExternal: ['nanoid'] },
  },
  integrations: [
    starlight({
      title: 'Snug Protocol',
      description:
        'An open protocol for user-built micro apps that think through their host agent at runtime.',
      logo: { src: './src/assets/snug-mark.svg', alt: '' },
      favicon: '/favicon.svg',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/snugprotocol' },
      ],
      customCss: ['./src/styles/starlight-theme.css'],
      sidebar: [
        { label: 'Overview', slug: 'docs' },
        {
          label: 'Get started',
          items: [
            { label: 'What is Snug?', slug: 'docs/get-started/what-is-snug' },
            { label: 'Try it in five minutes', slug: 'docs/get-started/quickstart' },
            { label: 'Build your first app', slug: 'docs/get-started/first-app' },
            { label: 'Implementor quickstart', slug: 'docs/get-started/implementors' },
          ],
        },
        {
          label: 'Core concepts',
          items: [
            { label: 'Envelopes & frames', slug: 'docs/concepts/envelopes-and-frames' },
            { label: 'The user file (.snug)', slug: 'docs/concepts/the-user-file' },
            { label: 'Connections & credentials', slug: 'docs/concepts/connections' },
            { label: 'Runtime contracts', slug: 'docs/concepts/runtime-contracts' },
          ],
        },
        {
          label: 'Build an implementation',
          items: [
            { label: 'Host a hub client', slug: 'docs/build/hub-client' },
            { label: 'Embed Snug in your product', slug: 'docs/build/embed' },
          ],
        },
        {
          // Generated by scripts/sync-spec.mjs from docs/spec-drafts/ + the protocol
          // schemas — autogenerated so a new spec Part can never drift from this list.
          label: 'Specification',
          autogenerate: { directory: 'docs/spec' },
        },
        { label: 'Whitepaper', slug: 'docs/whitepaper' },
      ],
    }),
  ],
});
