// astro.config.mjs — the public website: marketing pages + the /docs hub (ADR-0048).
//
// Starlight owns everything under src/content/docs/; the extra `docs/` folder inside it
// is what namespaces the hub under /docs (Starlight derives routes from file paths, so
// content/docs/docs/get-started.md → /docs/get-started). Astro pages (src/pages/) carry
// the marketing surfaces: /, /download.
//
// The `@playground` alias mirrors apps/desktop's: the website consumes playground
// source (releaseChannel.ts constants, theme tokens) read-only — never the reverse
// (ADR-0047 §2 dependency direction).
import { defineConfig } from 'astro/config';
import { unified } from '@astrojs/markdown-remark';
import starlight from '@astrojs/starlight';
import rehypeExternalLinks from 'rehype-external-links';
import { fileURLToPath } from 'node:url';

const playgroundSrc = fileURLToPath(new URL('../playground/src', import.meta.url));

export default defineConfig({
  site: 'https://snugprotocol.org',
  // Every absolute-URL link in rendered Markdown/MDX content opens in a new tab
  // (owner call, 2026-08-23): docs prose links to GitHub/the playground, and a
  // same-tab hop navigates the reader out of the docs. Root-relative internal
  // links are untouched (the plugin only matches protocol-carrying hrefs).
  // Astro 7 renders Markdown with Sätteri by default and deprecated the
  // `markdown.rehypePlugins` shorthand; `unified()` from @astrojs/markdown-remark keeps
  // the remark/rehype pipeline (and this plugin) on the supported path.
  markdown: {
    processor: unified({
      rehypePlugins: [[rehypeExternalLinks, { target: '_blank', rel: ['noopener'] }]],
    }),
  },
  vite: {
    resolve: {
      alias: { '@playground': playgroundSrc },
    },
  },
  integrations: [
    starlight({
      title: 'Snug Protocol',
      description:
        'An open protocol for user-built micro apps that think through their host agent at runtime.',
      logo: { src: './src/assets/snug-mark.svg', alt: '' },
      favicon: '/favicon.svg',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/snugprotocol' },
      ],
      customCss: ['./src/styles/starlight-theme.css'],
      components: {
        // The stock SocialIcons renders the header GitHub icon without target="_blank"
        // (same owner call) — the override is the same icon with the one attribute,
        // reading the single-homed site config.
        SocialIcons: './src/components/HeaderSocialIcons.astro',
        // Starlight generates every OG tag EXCEPT og:image, so the docs hub and the whole
        // rendered spec advertised a large-image card pointing at nothing. The override
        // renders Starlight's stock head and appends the image tags only.
        Head: './src/components/Head.astro',
      },
      sidebar: [
        { label: 'Overview', slug: 'docs' },
        {
          label: 'Get started',
          items: [
            { label: 'What is Snug?', slug: 'docs/get-started/what-is-snug' },
            { label: 'Try it in five minutes', slug: 'docs/get-started/quickstart' },
            { label: 'Build your first app', slug: 'docs/get-started/first-app' },
            { label: 'Implementor quickstart', slug: 'docs/get-started/implementors' },
          ],
        },
        {
          label: 'Core concepts',
          items: [
            { label: 'Envelopes & frames', slug: 'docs/concepts/envelopes-and-frames' },
            { label: 'The user file (.snug)', slug: 'docs/concepts/the-user-file' },
            { label: 'Connections & credentials', slug: 'docs/concepts/connections' },
            { label: 'Runtime contracts', slug: 'docs/concepts/runtime-contracts' },
          ],
        },
        {
          label: 'Build an implementation',
          items: [
            { label: 'Host a hub client', slug: 'docs/build/hub-client' },
            { label: 'Embed Snug in your product', slug: 'docs/build/embed' },
          ],
        },
        {
          // Generated by scripts/sync-spec.mjs from docs/spec-drafts/ + the protocol
          // schemas — autogenerated so a new spec Part can never drift from this list.
          // Starlight 0.39 removed `label` beside `autogenerate`: a named group now
          // wraps the autogenerate config in its own `items` array.
          label: 'Specification',
          items: [{ autogenerate: { directory: 'docs/spec' } }],
        },
        { label: 'Whitepaper', slug: 'docs/whitepaper' },
      ],
    }),
  ],
});
