// sync-spec.mjs — generates the website's spec pages from in-repo sources and
// (re)writes the docs-sync manifest (ADR-0048 §3–4).
//
// Sources (never the downstream snugprotocol/spec clone — C3):
//   - docs/spec-drafts/SPEC-1.0.md         → /docs/spec/* (split per Part + appendices)
//   - packages/protocol/schemas/*.json     → /docs/spec/schemas
//   - docs/whitepaper/dist/*.pdf           → public/whitepaper/ (served verbatim)
//
// Generated pages are VERBATIM splits — normative prose is never paraphrased here
// (lessons 2026-08-07: a derived document is checked by diffing sets and modality;
// verbatim rendering is the structural guard). Each carries a GENERATED marker.
//
// The manifest also records the AUTHORED pages' declared sources (mapping lives in
// AUTHORED_PAGES below — one home), so scripts/check-website-sync.mjs can flag any
// source drift at the root test gate.
import { createHash } from 'node:crypto';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const WEBSITE = resolve(fileURLToPath(new URL('..', import.meta.url)));
const REPO = resolve(WEBSITE, '..', '..');
const SPEC_SOURCE = 'docs/spec-drafts/SPEC-1.0.md';
const SCHEMA_DIR = 'packages/protocol/schemas';
const WHITEPAPER_PDF = 'docs/whitepaper/dist/snug-protocol-whitepaper.pdf';
const SPEC_OUT = join(WEBSITE, 'src', 'content', 'docs', 'docs', 'spec');

const GENERATED_MARK =
  '<!-- GENERATED by apps/website/scripts/sync-spec.mjs — do not edit by hand; run `pnpm --filter website sync-docs` -->';

const SPEC_BANNER =
  'Specification 1.0 — normative. One section (§17, standing approvals) is explicitly provisional and so marked.';

/**
 * Authored pages and the sources they must track. When one of these sources moves,
 * the root gate goes red and /sync-website walks the page against the change.
 */
const AUTHORED_PAGES = [
  { page: 'apps/website/src/pages/index.astro', sources: ['docs/product-vision.md'] },
  { page: 'apps/website/src/pages/download.astro', sources: ['docs/product-vision.md'] },
  { page: 'apps/website/src/content/docs/docs/index.mdx', sources: ['docs/product-vision.md'] },
  {
    page: 'apps/website/src/content/docs/docs/get-started/what-is-snug.md',
    sources: ['docs/product-vision.md', SPEC_SOURCE],
  },
  {
    page: 'apps/website/src/content/docs/docs/get-started/quickstart.mdx',
    sources: ['README.md'],
  },
  {
    page: 'apps/website/src/content/docs/docs/get-started/first-app.md',
    sources: [SPEC_SOURCE, 'packages/sdk/src/types.ts'],
  },
  {
    page: 'apps/website/src/content/docs/docs/get-started/implementors.md',
    sources: ['README.md', SPEC_SOURCE],
  },
  {
    page: 'apps/website/src/content/docs/docs/concepts/envelopes-and-frames.md',
    sources: [SPEC_SOURCE],
  },
  {
    page: 'apps/website/src/content/docs/docs/concepts/the-user-file.md',
    sources: [SPEC_SOURCE],
  },
  {
    page: 'apps/website/src/content/docs/docs/concepts/connections.md',
    sources: [SPEC_SOURCE],
  },
  {
    page: 'apps/website/src/content/docs/docs/concepts/runtime-contracts.md',
    sources: [SPEC_SOURCE],
  },
  { page: 'apps/website/src/content/docs/docs/build/hub-client.md', sources: [SPEC_SOURCE] },
  { page: 'apps/website/src/content/docs/docs/build/embed.md', sources: [SPEC_SOURCE] },
  {
    page: 'apps/website/src/content/docs/docs/whitepaper.mdx',
    sources: [WHITEPAPER_PDF],
  },
];

function sha256(path) {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

function frontmatter(title, order, description, sidebarLabel) {
  const lines = ['---', `title: "${title.replace(/"/g, '\\"')}"`];
  if (description) lines.push(`description: "${description.replace(/"/g, '\\"')}"`);
  lines.push('sidebar:', `  order: ${order}`);
  if (sidebarLabel) lines.push(`  label: "${sidebarLabel}"`);
  lines.push('banner:', `  content: "${SPEC_BANNER}"`);
  lines.push('---', '');
  return lines.join('\n');
}

/** Split the one-file spec draft on `# ` headings into ordered sections. */
function splitSpec(text) {
  const lines = text.split('\n');
  const sections = [];
  let current = null;
  let inFence = false;
  for (const line of lines) {
    if (/^```/.test(line)) inFence = !inFence;
    if (!inFence && /^# /.test(line)) {
      if (current) sections.push(current);
      current = { heading: line.replace(/^# /, '').trim(), body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) sections.push(current);
  return sections;
}

function slugForSection(heading, index) {
  const part = heading.match(/^Part ([IVX]+)/);
  if (part) {
    const rest = heading
      .replace(/^Part [IVX]+\s*[—-]\s*/, '')
      .split(':')[0]
      .toLowerCase()
      .replace(/\(.*?\)/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    return `part-${index}-${rest}`;
  }
  return null; // appendices are combined into one page
}

// --- generate ---------------------------------------------------------------

const specText = readFileSync(join(REPO, SPEC_SOURCE), 'utf8');
const sections = splitSpec(specText);
const preamble = sections[0]; // the document title + stability + conventions
const parts = sections.filter((s) => /^Part /.test(s.heading));
const appendices = sections.filter((s) => /^Appendix /.test(s.heading));

rmSync(SPEC_OUT, { recursive: true, force: true });
mkdirSync(SPEC_OUT, { recursive: true });

const generatedEntries = [];
const specHash = sha256(join(REPO, SPEC_SOURCE));

function writeSpecPage(fileName, title, order, bodyMarkdown, description, sidebarLabel) {
  const outPath = join(SPEC_OUT, fileName);
  const content = `${frontmatter(title, order, description, sidebarLabel)}${GENERATED_MARK}\n\n${bodyMarkdown.trim()}\n`;
  writeFileSync(outPath, content);
  generatedEntries.push({
    page: join('apps/website/src/content/docs/docs/spec', fileName).split('\\').join('/'),
    kind: 'generated',
    sources: [{ path: SPEC_SOURCE, sha256: specHash }],
  });
}

// index page: preamble + a part directory
const partList = parts
  .map((p, i) => `- [${p.heading}](/docs/spec/${slugForSection(p.heading, i + 1)}/)`)
  .join('\n');
writeSpecPage(
  'index.md',
  'Specification',
  0,
  [
    preamble.body.join('\n').trim(),
    '',
    '## The document',
    '',
    partList,
    `- [Appendices — error codes, constants, published schemas](/docs/spec/appendices/)`,
    `- [Schema reference](/docs/spec/schemas/)`,
    '',
    '> Rendered verbatim from the reference implementation\u2019s specification',
    '> (`docs/spec-drafts/SPEC-1.0.md`). The published record lives in',
    '> [snugprotocol/spec](https://github.com/snugprotocol/spec).',
  ].join('\n'),
  'The Snug Protocol specification, 1.0.',
  'Spec overview',
);

parts.forEach((part, i) => {
  writeSpecPage(`${slugForSection(part.heading, i + 1)}.md`, part.heading, i + 1, part.body.join('\n'));
});

writeSpecPage(
  'appendices.md',
  'Appendices',
  parts.length + 1,
  appendices.map((a) => `## ${a.heading}\n${a.body.join('\n')}`).join('\n\n'),
);

// schema reference
const schemaFiles = readdirSync(join(REPO, SCHEMA_DIR))
  .filter((f) => f.endsWith('.json'))
  .sort();
const schemaSections = schemaFiles.map((file) => {
  const raw = readFileSync(join(REPO, SCHEMA_DIR, file), 'utf8');
  const parsed = JSON.parse(raw);
  const description = parsed.description ? `\n${parsed.description}\n` : '';
  return `## ${file.replace(/\.json$/, '')}\n${description}\n\`\`\`json\n${raw.trim()}\n\`\`\``;
});
const schemasPage = [
  'Machine-readable JSON Schemas for every protocol message, published byte-identical',
  'from the reference implementation (`packages/protocol/schemas/`). A validator passing',
  'a schema has not validated the frame — some normative rules (refinements) are not',
  'expressible in JSON Schema; the spec text governs.',
  '',
  ...schemaSections,
].join('\n');
const schemasOut = join(SPEC_OUT, 'schemas.md');
writeFileSync(
  schemasOut,
  `${frontmatter('Schema reference', parts.length + 2, 'JSON Schemas for all Snug Protocol frames.')}${GENERATED_MARK}\n\n${schemasPage}\n`,
);
generatedEntries.push({
  page: 'apps/website/src/content/docs/docs/spec/schemas.md',
  kind: 'generated',
  sources: schemaFiles.map((f) => ({
    path: `${SCHEMA_DIR}/${f}`,
    sha256: sha256(join(REPO, SCHEMA_DIR, f)),
  })),
});

// whitepaper PDF → public/
const pdfSource = join(REPO, WHITEPAPER_PDF);
if (!existsSync(pdfSource)) {
  console.error(`sync-spec: whitepaper PDF missing at ${WHITEPAPER_PDF} — build it first`);
  process.exit(1);
}
mkdirSync(join(WEBSITE, 'public', 'whitepaper'), { recursive: true });
copyFileSync(pdfSource, join(WEBSITE, 'public', 'whitepaper', 'snug-protocol-whitepaper.pdf'));
generatedEntries.push({
  page: 'apps/website/public/whitepaper/snug-protocol-whitepaper.pdf',
  kind: 'generated',
  sources: [{ path: WHITEPAPER_PDF, sha256: sha256(pdfSource) }],
});

// --- manifest ---------------------------------------------------------------

const authoredEntries = AUTHORED_PAGES.map((entry) => ({
  page: entry.page,
  kind: 'authored',
  sources: entry.sources.map((path) => ({ path, sha256: sha256(join(REPO, path)) })),
}));

const manifest = { generatedAt: 'sync-spec.mjs', entries: [...generatedEntries, ...authoredEntries] };
writeFileSync(join(WEBSITE, 'docs-sync.json'), `${JSON.stringify(manifest, null, 2)}\n`);

console.log(
  `sync-spec: wrote ${generatedEntries.length} generated pages/assets, manifest tracks ${manifest.entries.length} pages`,
);
